### ISSUE TITLE
push access upload form

### ISSUE THREAD

**Issue by Ausforam** [square/connect-api-examples#105]

**Comment by StephenJosey** [comment]
I'm not sure what the request or issue is here. Can you please reply back with a description of the issue you encountered? Thanks!

**Comment by Ausforam** [comment]
on Step 1 for adding pyment online : Download basic payment form templates from GitHub
the forms are disabled.

**Comment by StephenJosey** [comment]
What do you mean by disabled? Are they not loading? Did you input your Square application id and location id? Are you receiving console errors within your browser? Thanks!
