### ISSUE TITLE
zip code numeric pad for café orders

### ISSUE THREAD

**Issue by CDIDEV** [square/connect-api-examples#111]
The Payment form for the Zip Code field defaults to the alpha keyboard. This is fine for international (Canadian) zip codes, but we are only supporting the US.
Is there a way that we can default to only show the numeric key pad?  If not, can this be fixed please?
This is for both iOS and Android devices.

**Comment by CDIDEV** [comment]
Could someone from Square follow up on this issue please. Thanks!

**Comment by StephenJosey** [comment]
Sorry for the delay, but unfortunately this is not currently possible. I'll definitely relay this feedback to the appropriate team, though.
