### ISSUE TITLE
Generate Nonce with API

### ISSUE THREAD

**Issue by tamanneupane** [square/connect-api-examples#116]
Hello ,

We are testing your payment sdk , We have our own card reading device. Is there any api or any way so that we can generate nonce with the card information we get after swiping card to our reader? We are getting Track1 , Track2 , Track3 for magnetic card and UUID  , ATR for IC card.  We are testing it in Android application.

**Comment by StephenJosey** [comment]
No, currently the only way to generate a nonce via Square is by using the Square Payment Form.

**Comment by tamanneupane** [comment]
Are you planning to provide such API in near future ?

**Comment by StephenJosey** [comment]
Unfortunately we don't publish public timelines of our releases. If a release does happen, you'll be able to find out in our docs (or by signing up to our Developers newsletter: https://www.workwithsquare.com/developer-newsletter.html). Thanks!

**Comment by ohtaeksoo** [comment]
Very odd. Missing the core value from API.  The API would be more valuable and powerful if Nonce could be generated with API.
