### ISSUE TITLE
Random div element junk added to DOM 

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-examples#132]
Some random `div` element (`<div id="30713c77-4f4e-8793-4711-5cb26224444b"></div>`) was added to my site's DOM after the transaction was successful. My web platform's code is extremely strict and this random `div` appeared as a modal. The `id` looks randomly generated and there are no other attributes to select the element without spending about an hour doing a lot of deductive JavaScript to find and hide this random `div`.

Should this `div` even be added to my site's DOM for any actually legitimate reason? If so why isn't it set to `display: none;` or at least something such as `style="opacity: 0;"`?

**Comment by StephenJosey** [comment]
Hey @jabcreations thanks for sharing! This should not be happening, so we're looking into it and will follow-up once we have more information.

**Comment by StephenJosey** [comment]
Hey @jabcreations this should be resolved, now. Please let me know if this issue is still occurring, but for now I'll be closing this. Thanks, again, for reporting this!
