### ISSUE TITLE
Confusion between nonce and IDs

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-examples#133]
There is some confusion between when to submit a `card_nonce` and when to instead submit the `customer_card_id` and `customer_id`.

I was submitting the nonce for saved cards without realizing that I should have been submitting `customer_card_id` and `customer_id`; if a server submits a nonce for a card already on file (for a saved user) Square should instead respond to *not* submit the nonce and to use the other two fields. That would save a lot of people a lot of frustration.

Perhaps a very basic flow chart? If you're not saving the customer's information submit the `card_nonce`. If you are submit the `customer_card_id` and `customer_id`.

**Comment by StephenJosey** [comment]
Hey @jabcreations thanks for the feedback! I know we have a [step-by-step layout ](https://docs.connect.squareup.com/payments/transactions/overview#how-it-works-the-transactions-api-process-flow)of how the Transactions API works, and it does mention using a customer card ID for a previously saved card (as well as a graphic flow-chart after it). Is this something you had in mind, or would you still like it more geared to the difference between the nonce and card id?

**Comment by jabcreations** [comment]
> The client server creates a Transaction request object using a customer card ID nonce stored previously or a payment nonce generated with SqPaymentForm and calls the Charge endpoint.

Unfortunately this is still too ambiguous. I have been working on-and-ff on the Square payment form for a good part of almost two years, something more explicit should be used. Here is an example of what I have in mind:

>The client server creates a Transaction request object using *either* the customer card ID (required for saved customer cards) stored previously or a payment nonce generated with SqPaymentForm (required if the customer's information is not being saved) and calls the Charge endpoint.

It would also help to have a side-by-side *minimally viable* sets of JSON to be sent to the Square servers in each circumstance as examples with headers "Customer's Information Saved" and "One-Time Transactions Only".

**Comment by StephenJosey** [comment]
Great, thanks for your feedback! I'll share this with our documentation team.
