### ISSUE TITLE
IdempotencyKey expiration

### ISSUE THREAD

**Issue by kksd** [square/connect-api-examples#135]
We observe a case where two BatchChangeInventory requests with the same idempotencyKey resulted in two changes records, as a result, the quantity has been doubled.

Is there an expiration time for idempotencyKey?

**Comment by StephenJosey** [comment]
As far as I know they do not expire. With that said, you should always use a unique idempotency key when you're doing a new, unique, request. We highly recommend using a UUID which is guaranteed to be unique. 

With that said, do you have the `idempotency_key` that was used per chance? When using the same idempotency key you should always receive the same response as the initial time. If you use the same idempotency key and change the request, you should receive an error similar to "duplicate idempotency token used with different request body".
