### ISSUE TITLE
Request not authorized

### ISSUE THREAD

**Issue by itslenny** [square/connect-api-examples#148]
I'm trying to get the `node_orders-payments` project working.

I set up my sandbox credentials and seeded the menu without an issue.

The entire order flow goes great. Then when I click "Pay with card" I get the error `Request not authorized`.

Looking at the network tab I can see it's making a call to `https://pci-connect.squareupsandbox.com/v2/card-nonce` and returning a 401 Unauthorized.

This is the request body that is sent to that endpoint.

```
card_data: { number: "4111111111111111", exp_month: 12, exp_year: 2021, cvv: "111", billing_postal_code: "98101" }
client_id: "REMOVED"
location_id: "REMOVED"
session_id: "REMOVED"
squarejs_version: "db4f5f246a"
website_url: "http://localhost:3000"
```

**Comment by mootrichard** [comment]
I would double check that you have your Sandbox App ID set for the Sandbox credentials, since in testing this, you can have that happen if you try to use a Prod APP ID for Sandbox.
```
{
  "sandbox": {
    "path": "https://connect.squareupsandbox.com",
    "squareApplicationId": "SANDBOX_APP_ID",
    "squareAccessToken": "SANDBOX_ACCESS_TOKEN"
  },
  "production": {
    "path": "https://connect.squareup.com",
    "squareApplicationId": "PRODUCTION_APP_ID",
    "squareAccessToken": "PRODUCTION_ACCESS_TOKEN"
  }
}
```

**Comment by itslenny** [comment]
@mootrichard Thanks for the response. I'm pretty sure the credentials are correct as the seed command succeeded. In fact the entire order flow succeeds until the very last screen. I get that error on the very last step of the process when I click checkout. I don't have production credentials entered. Only sandbox, and I started the app using `npm test`

**Comment by mootrichard** [comment]
Hmmm, the only way that I was able to replicate this issue on my end was by putting my `"sandbox": { "squareApplicationId": PRODUCTION_ID  }`. Then it would give me a 401. 

Does the ID that you have entered in there start with `sandbox`? If so, we definitely need to investigate further as to why you're getting a 401.

**Comment by anshilbhansali** [comment]
I am experiencing the exact same thing. Pretty sure I have put in the right credentials in the config.json and the entire order flow works until the payment. 

I also get an 401 response on https://connect.squareupsandbox.com/v2/analytics/token on the checkout page

**Comment by mootrichard** [comment]
I've tried to configure this is multiple combinations to replicate the issues being described, but the only way I've been able to get this 401 unauthorized to occur is when I have a mismatch between my APP_ID and target environment (production vs sandbox). 

Do you have a working example I could use to test and try to replicate?

**Comment by vchavarha-i** [comment]
There also should be a parameter that I do not see `analytics_token`
It is requested when you set up your square payment form. 
Since it is not there your square payment form might not be initialized correctly
Check if you supplied  correct square url. You might have sent production url and request your nonce via sandbox or vise versa.

**Comment by harrisonsuarez** [comment]
I had this issue also. I solved it by making sure that I was passing the `sandbox={true}` prop.

Like @anshilbhansali, my calls to https://connect.squareupsandbox.com/v2/analytics/token were returning 401 responses. I inspected one in the network tab and found an error message, something to the effect of, "You're using a sandbox token in a production environment."

After passing the boolean, the 401 error to analytics went away and the nonce generation calls started to succeed.

**Comment by NanoMeko** [comment]
same issue

**Comment by berksites** [comment]
Double check you are loading https://js.squareupsandbox.com/v2/paymentform for sandbox transactions rather than https://js.squareup.com/v2/paymentform for production.

**Comment by NanoMeko** [comment]
Yeap I think that was it or something similar. All good now.

**Comment by dparvanov** [comment]
> Double check you are loading https://js.squareupsandbox.com/v2/paymentform for sandbox transactions rather than https://js.squareup.com/v2/paymentform for production. Token error

My issue was due to loading https://js.squareupsandbox.com/v2/paymentform and https://js.squareup.com/v2/paymentform at the same time.

**Comment by Jack-Moon628** [comment]
Hello, everyone.
I have the same issue in my project, and I want to know exactly which file should be changed to this
```
{
  "sandbox": {
    "path": "https://connect.squareupsandbox.com",
    "squareApplicationId": "SANDBOX_APP_ID",
    "squareAccessToken": "SANDBOX_ACCESS_TOKEN"
  },
  "production": {
    "path": "https://connect.squareup.com",
    "squareApplicationId": "PRODUCTION_APP_ID",
    "squareAccessToken": "PRODUCTION_ACCESS_TOKEN"
  }
}
```
