### ISSUE TITLE
how charge the credit card

### ISSUE THREAD

**Issue by atmangel** [square/connect-api-examples#157]
Hi, in php_payment example how i can charge the credit card? i see you use only 2 parameters: amount and currency,  but credit-card number, cvv, and expiry parameters is not used in any place in code.

  "amount_money" => array (
    "amount" => 100,
    "currency" => "USD"
  )

**Comment by atmangel** [comment]
I see you generate a nonce from credit card data, but i dont see where is generate this nonce

in sq-payment-form.js is a function

cardNonceResponseReceived: function(errors, nonce, cardData, billingContact, shippingContact)

this function inserts the nonce in div with id "card-nonce" but i see not where this functions is used.

**Comment by havenwood** [comment]
The card token nonce comes from the Payment Form. I'd suggest following the [Payment Form Walkthrough](https://developer.squareup.com/docs/payment-form/payment-form-walkthrough#step-1-generate-a-secure-single-use-token-nonce) to get up to speed with how that works.

Once you have your card token nonce, you can add it as the `source_id` to charge the payment. There is an example of adding a card token nonce as the source ID [on this line](https://github.com/square/connect-api-examples/blob/8a5b07c1df8d8c38bce68107e75a39d4501a7f5e/connect-examples/v2/php_payment/process-card.php#L53).

If you have follow-up questions, we'd be happy to answer then in our [Square developer community chat](https://squ.re/slack). Please join us there!

**Comment by atmangel** [comment]
Your code ir very confused, better i go to stripe, his examples are much easier to understand. Bye and thanks
