### ISSUE TITLE
Error 404 when DELETE a payment

### ISSUE THREAD

**Issue by miketran78727** [square/connect-api-examples#18]
I used the python sample code for listing payments and it worked great. I am wondering if deleting a payment is possible with version 1 API.  I got error 404 with this code:
````
	connection = httplib.HTTPSConnection('connect.squareup.com')
	request_headers = {'Authorization': 'Bearer ' + access_token,
		'Accept':        'application/json',
		'Content-Type':  'application/json'}
	request_path = "/v1/" + locationID + "/payments/" + id
	connection.request('DELETE', request_path, '', request_headers)
````

**Comment by bunnyc1986** [comment]
Payment cannot be deleted. The API reference can be found: https://docs.connect.squareup.com/api/connect/v1/
