### ISSUE TITLE
Typo in Node.js documentation

### ISSUE THREAD

**Issue by juliettech13** [square/connect-api-examples#182]
On [Node.js documentation](https://github.com/square/connect-api-examples/tree/master/connect-examples/v2/node_payment), there is a typo stating `respone` rather than `response` in the last section of the document:
```
  try {
    const **respone** = await payments_api.createPayment(request_body);
    const json = JSON.stringify(**respone**);
    res.render('process-payment', {
      'title': 'Payment Successful',
      'result': json
    });
  } catch (error) {
    res.render('process-payment', {
      'title': 'Payment Failure',
      'result': error.**response**.text
    });
  }
});
...
```

**Comment by StephenJosey** [comment]
Thanks for reporting! Fixed here: https://github.com/square/connect-api-examples/pull/184
