### ISSUE TITLE
C# payment example

### ISSUE THREAD

**Issue by petespatio** [square/connect-api-examples#33]
I am trying the C# example, i enter credit card information -
4532 7597 3454 5858
111
12/20
88888
When i press the submit query button i get -
Invalid applicationId

I don't see where in this example i enter my applicationID?

Please help.

**Comment by alecholmes** [comment]
You set it when you initialize the Javascript form: https://github.com/square/connect-api-examples/blob/master/connect-examples/v2/csharp_payment/PaymentExample/Default.aspx#L14
