### ISSUE TITLE
Connect API C# Payment Example

### ISSUE THREAD

**Issue by petespatio** [square/connect-api-examples#35]
I am trying to figure out what this error means.
Error calling Charge: {"errors":[{"category":"AUTHENTICATION_ERROR","code":"UNAUTHORIZED","detail":"This request could not be authorized."}]}

I get a valid nonce.
When i call the Charge method, I use my sandbox access token and a location ID that i get when i run the curl command to get the location id.
curl -H "Authorization: Bearer sandbox-sq0atb-emlxxxxxxxxxx" https://connect.squareup.com/v2/locations

        public static string Charge(string nonce)
        {
            Configuration.Default.AccessToken = "Authorization: Bearer sandbox-sq0atb-emlxxxxxxxxxx";

            // Every payment you process with the SDK must have a unique idempotency key.
            // If you're unsure whether a particular payment succeeded, you can reattempt
            // it with the same idempotency key without worrying about double charging
            // the buyer.
            string uuid = NewIdempotencyKey();

            // Monetary amounts are specified in the smallest unit of the applicable currency.
            // This amount is in cents. It's also hard-coded for $1.00,
            // which isn't very useful.
            Money amount = new Money(100, Money.CurrencyEnum.USD);

            ChargeRequest body = new ChargeRequest(AmountMoney: amount, IdempotencyKey: uuid, CardNonce: nonce);

            try
            {
                var response = _transactionsApi.Charge(_locationId2, body);
                return "Transaction complete\n" + response.ToJson();
            }
            catch (ApiException e)
            {
                return e.Message;
            }
        }

Regards

**Comment by frojasg** [comment]
could replace this line:
```c#
Configuration.Default.AccessToken = "Authorization: Bearer sandbox-sq0atb-emlxxxxxxxxxx";
```
with the following line: 

```c#
Configuration.Default.AccessToken = "sandbox-sq0atb-emlxxxxxxxxxx";
```

**Comment by petespatio** [comment]
Thanks Francisco
There is something wrong with my sandbox credentials. I was able to get it to run locally with a valid CC.

Dave
