### ISSUE TITLE
How to transaction id after successful payment

### ISSUE THREAD

**Issue by sandeepsoni214** [square/connect-api-examples#36]
# The SDK throws an exception if a Connect endpoint responds with anything besides
# a 200-level HTTP code. This block catches any exceptions that occur from the request.
try {

    $result = $transactions_api->charge($location->getId(), $request_body);

    file_put_contents("text.txt", $result);

//How to get Transaction , from above $result variation for saving db purpose

    echo "<pre>";
    print_r($result);
    echo "</pre>";
} catch (\SquareConnect\ApiException $e) {
    echo "Caught exception!<br/>";
    print_r("<strong>Response body:</strong><br/>");
    echo "<pre>";
    var_dump($e->getResponseBody());
    echo "</pre>";
    echo "<br/><strong>Response headers:</strong><br/>";
    echo "<pre>";
    var_dump($e->getResponseHeaders());
    echo "</pre>";
}

**Comment by StephenJosey** [comment]
Yes, the SDK will throw an error if the transaction was not successful. If the transaction was successful, you should be able to use:
```
$result = $transactions_api->charge($location->getId(), $request_body);
print_r($result->getTransaction()->getId()); // this will print the transaction_id
```
