### ISSUE TITLE
Vulnerability in Node example?

### ISSUE THREAD

**Issue by SebassCoates** [square/connect-api-examples#362]
https://github.com/square/connect-api-examples/blob/master/connect-examples/oauth/node/index.js

Using the current date to generate a "random" Auth_State seems problematic (line 91). The built-in NodeJS crypto library provides a random bytes function that would more closely mirror the PHP example.

**Comment by zenmasterjobo** [comment]
Hi @SebassCoates 

Thanks for calling this out. I went ahead and updated that piece of code
