### ISSUE TITLE
Charge error

### ISSUE THREAD

**Issue by petespatio** [square/connect-api-examples#47]
I am using the v2 c# API.

When you call charge and you get an error such as VERIFY_AVS_FAILURE.
In this case the zip code was bad - 99999.

Do you have to change your idempotency_key to process the card after the zip code was corrected?

**Comment by tristansokol** [comment]
Yep! In general, you want your idempotency key to be unique for each request, so if you correct a bad zip code, you'll be charging with a new `card_nonce`, and making a different request. Hope that helps! 

Don't forget about our tag `square-connect` on [StackOverflow](https://stackoverflow.com/questions/tagged/square-connect), it can be a better place for questions like this.
