### ISSUE TITLE
Update python examples to use the connect-python-sdk library

### ISSUE THREAD

**Issue by calebpsdinc** [square/connect-api-examples#48]
I'm getting some odd errors and looking for an example of how to use the library to make calls to the V1Transaction API's list_payment. The examples in this repo do not use the square-provided connect-python-sdk library so they don't transfer over well to one who is using the library.

**Comment by StephenJosey** [comment]
We do have a Python example that uses the Python SDK, but for V2, not for V1. For information on how to use list_payments with the Python SDK, please look at: https://github.com/square/connect-python-sdk/blob/master/docs/V1TransactionsApi.md#list_paymentss

Please let us know if you still have any questions after reviewing the SDK docs!
