### ISSUE TITLE
Improvement: Purchase history by customer_id

### ISSUE THREAD

**Issue by justincohler** [square/connect-api-examples#5]
Expose an endpoint to list customer transactions and the list of items purchased in each transaction.

Example Documentation:

> `GET /v2/customers/{customer_id}/transactions`
> 
> Lists transactions for a particular customer.
> 
> Max results per [page](https://docs.connect.squareup.com/api/connect/v2/#paginatingresults): 50
> 
> Required [permissions](https://docs.connect.squareup.com/api/connect/v2/#usingoauth): `CUSTOMERS_READ`

**Comment by StephenBarlow** [comment]
Thanks for the feature request! I've passed it along to the API engineering team for prioritization.

**Comment by bunnyc1986** [comment]
thanks for the suggestion.
