### ISSUE TITLE
Backward logic on example-confirm-transaction.php

### ISSUE THREAD

**Issue by JRichmond27** [square/connect-api-examples#53]
I'm not a PHP dev, so I could be wrong, but I'm pretty sure the conditional logic is backwards on line 36. 

https://github.com/square/connect-api-examples/blob/2497a7f67879cdb54806bad04ff0e3a7dc90f4b5/connect-examples/v2/php_checkout/templates/example-confirm-transaction.php#L36-L53

```
if invalid transaction 
    show order confirmation
else 
    show error message
```

**Comment by yonpols** [comment]
You're right. We'll fix it
