### ISSUE TITLE
File or function missing

### ISSUE THREAD

**Issue by ashwani737** [square/connect-api-examples#55]
I have downloaded your sample code in local host. I have downloaded the code from this location. connect-api-examples/connect-examples/v2/php_payment/

After modifying in js file and php file if I run the code its giving me this error. 
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\sq_payment_gateway\process-card.php on line 2

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\sq_payment_gateway\process-card.php on line 2

Please provide us the vendor flder as well so that we can test a dummy transaction on localhost and then move to production.

If i comment out this line of code require 'vendor/autoload.php'; then its giving me this error.

Fatal error: Uncaught Error: Class 'SquareConnect\Configuration' not found in C:\xampp\htdocs\sq_payment_gateway\process-card.php:22 Stack trace: #0 {main} thrown in C:\xampp\htdocs\sq_payment_gateway\process-card.php on line 22

I tried a lot to find where is vendor folder but couldn't find it.

I hope you got the concern. Please provide us the missing file.

**Comment by DanielNi** [comment]
@ashwani737 The vendor folder is automatically created when you install the project dependencies using Composer. See the [Install the PHP client library](https://github.com/square/connect-api-examples/tree/master/connect-examples/v2/php_payment) section of the README.md for how to download and use Composer to run the sample.
