### ISSUE TITLE
How to submit payment with SqPaymentForm?

### ISSUE THREAD

**Issue by danielbradburry** [square/connect-api-examples#57]
I run an application through which I allow clients to charge their customers via their gateway of choice, and Square has come up as a recommended option. I have thus been attempting to integrate for two weeks with no success. Your documentation appears to suggest that OAuth is the way to go, so I have created a link in my app that clients can trigger, then authorize Square as a gateway, which generates the token that I store. This works fine.

I am attempting to set up the payment form in my app from the PHP code samples here, with virtually no alteration save a token that I managed to generate. The sandbox token generates this reply:

`Caught exception!
Response body:
object(stdClass)#9 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#10 (4) {
      ["category"]=>
      string(21) "INVALID_REQUEST_ERROR"
      ["code"]=>
      string(26) "MISSING_REQUIRED_PARAMETER"
      ["detail"]=>
      string(27) "Missing required parameter."
      ["field"]=>
      string(10) "card_nonce"
    }
  }
}`

That's crazy, since 'card_nonce' is a parameter that isn't in one way referenced in any of these files or documentation. The production token is even better, causing a 500 error as $location->getId() collapses as $location is returned false. Mind you, I DO have a location with the production token, so the reason for this one is just as baffling.

I'm also wondering where/when I am supposed to inject the shopping cart items... in the JS or the PHP response?

I have previously submitted two requests for assistance through the contact form, and one generated no response while the other took 48 hours to answer a question I didn't ask. I also noticed that no matter how hard I try, it is impossible for me to get anyone with Square on the phone. Therefore raising an issue on Github appears to be my only remaining option.

**Comment by timtoyoshima** [comment]
Hi Daniel, I'm sorry that you've had a rough experience. Please contact me directly at timto@squareup.com and I'll make sure that we address your questions so that you can complete your integration. Thanks for the feedback and hope to connect with you soon. Thx Tim
