### ISSUE TITLE
Card-nonce not show

### ISSUE THREAD

**Issue by irfanwv** [square/connect-api-examples#6]
I am using same code, But when I submit form then card-nonce show empty.
I am trying to various way but not working, Can I generate card-nonce manually?

**Comment by dudefromtexas** [comment]
i am having the same issue.
the nonce post variable is showing as a key with no value.
then I try to use print_r($POST) to show value and show a key for nonce but no value

**Comment by StephenBarlow** [comment]
@irfanwv Thanks for reporting. Could you clarify the following:

- Which sample in the repo are you working with?
- Are you saying that the `SqPaymentForm` is not successfully generating a card nonce, or that the card nonce is not successfully being sent from your webpage to your server?

For security reasons, it is not possible to generate a card nonce except with the `SqPaymentForm`.

**Comment by StephenBarlow** [comment]
@dudefromtexas A couple questions for you to hopefully help diagnose:

- When you fill in your card form and click Submit, does an alert appear that includes both "Nonce received!" and the value of the card nonce?
- What browser and browser version are you using?
- Are you attempting to generate card nonces with your sandbox credentials or your live credentials?

**Comment by irfanwv** [comment]
@StephenBarlow I am using `square/connect-api-examples/tree/master/connect-examples/v2/php_payment` same script.

**Comment by undergod11** [comment]
I cannot get this to work and process card payments.

https://bizzahost.com/payments/square/

I get the card nonce and it does not charge the card.

**Comment by StephenBarlow** [comment]
@irfanwv @dudefromtexas @undergod11 Please contact [Square support](https://squareup.com/help/us/en/contact) with your issue so that we can better diagnose your respective issues. Be sure to select "Square API" as the product you are inquiring about.

**Comment by big89** [comment]
We have successfully integrated Square Payment Gateway With Sandbox in PHP. Let me know if anuone wants help.

**Comment by sunilkumarambala** [comment]
> @irfanwv @dudefromtexas @undergod11 Please contact [Square support](https://squareup.com/help/us/en/contact) with your issue so that we can better diagnose your respective issues. Be sure to select "Square API" as the product you are inquiring about.

Hiya

I am getting a problem in the payment form. I am not getting card-nonce and form submit without it.

I am using sandbox mode in the payment form.
I am referring https://developer.squareup.com/docs/payment-form/build-the-form?q=payment%20form#step-1-download-basic-payment-form-templates-from-github 

I am stuck in step 6 in the aforementioned link and in the last step I am not getting card-nonce.

I am getting response after form submit like this
Array
(
    [nonce] => 
)

this is my basic js script

// Set the application ID
var applicationId = "sandbox-sq0idp-kUk1pFj5eniBNPUZ94s5OA";
// Set the location ID
var locationId = "CBASEMDuBoNyNFa8T3s5EVgqJocgAQ";
/*function buildForm(form) {
  if (SqPaymentForm.isSupportedBrowser()) {
    form.build();
    form.recalculateSize();
  }
}*/
/*
 * function: requestCardNonce
 *
 * requestCardNonce is triggered when the "Pay with credit card" button is
 * clicked
 *
 * Modifying this function is not required, but can be customized if you
 * wish to take additional action when the form button is clicked.
 */
function requestCardNonce(event) {
    // Don't submit the form until SqPaymentForm returns with a nonce
    event.preventDefault();
    // Request a nonce from the SqPaymentForm object
    paymentForm.requestCardNonce()
}
// Create and initialize a payment form object
var paymentForm = new SqPaymentForm({
    // Initialize the payment form elements
    applicationId: applicationId,
    locationId: locationId,
    inputClass: 'sq-input',
    autoBuild: true,
    // Customize the CSS for SqPaymentForm iframe elements
    inputStyles: [{
        fontSize: '16px',
        fontFamily: 'Helvetica Neue',
        padding: '16px',
        color: '#373F4A',
        backgroundColor: 'transparent',
        lineHeight: '24px',
        placeholderColor: '#CCC',
        _webkitFontSmoothing: 'antialiased',
        _mozOsxFontSmoothing: 'grayscale'
    }],
    // Initialize Apple Pay placeholder ID
    applePay: false,
    // Initialize Masterpass placeholder ID
    masterpass: false,
    // Initialize the credit card placeholders
    cardNumber: {
        elementId: 'sq-card-number',
        placeholder: '• • • •  • • • •  • • • •  • • • •'
    },
    cvv: {
        elementId: 'sq-cvv',
        placeholder: 'CVV'
    },
    expirationDate: {
        elementId: 'sq-expiration-date',
        placeholder: 'MM/YY'
    },
    postalCode: {
        elementId: 'sq-postal-code',
        placeholder: '12345'
    },
    // SqPaymentForm callback functions
    callbacks: {
        /*
         * callback function: createPaymentRequest
         * Triggered when: a digital wallet payment button is clicked.
         * Replace the JSON object declaration with a function that creates
         * a JSON object with Digital Wallet payment details
         */
        createPaymentRequest: function() {
          console.log("request send");
            return {
                requestShippingAddress: false,
                requestBillingInfo: true,
                currencyCode: "GBR",
                countryCode: "UK",
                total: {
                    label: "sandeep",
                    amount: "100",
                    pending: false
                },
                lineItems: [{
                    label: "Subtotal",
                    amount: "100",
                    pending: false
                }]
            }
        },
        /*
         * callback function: cardNonceResponseReceived
         * Triggered when: SqPaymentForm completes a card nonce request
         */
        cardNonceResponseReceived: function(errors, nonce, cardData) {
          alert(nonce);
            if (errors) {
                // Log errors from nonce generation to the Javascript console
                console.log("Encountered errors:");
                errors.forEach(function(error) {
                    console.log('  ' + error.message);
                    alert(error.message);
                });
                return;
            }
            // Assign the nonce value to the hidden form field
            document.getElementById('card-nonce').value = nonce;
            // POST the nonce form to the payment processing page
            document.getElementById('nonce-form').submit();
        },
        /*
         * callback function: unsupportedBrowserDetected
         * Triggered when: the page loads and an unsupported browser is detected
         */
        unsupportedBrowserDetected: function() {
            /* PROVIDE FEEDBACK TO SITE VISITORS */
        },
        /*
         * callback function: inputEventReceived
         * Triggered when: visitors interact with SqPaymentForm iframe elements.
         */
        inputEventReceived: function(inputEvent) {
            switch (inputEvent.eventType) {
                case 'focusClassAdded':
                    /* HANDLE AS DESIRED */
                    break;
                case 'focusClassRemoved':
                    /* HANDLE AS DESIRED */
                    break;
                case 'errorClassAdded':
                    document.getElementById("error").innerHTML = "Please fix card information errors before continuing.";
                    break;
                case 'errorClassRemoved':
                    /* HANDLE AS DESIRED */
                    document.getElementById("error").style.display = "none";
                    break;
                case 'cardBrandChanged':
                    /* HANDLE AS DESIRED */
                    break;
                case 'postalCodeChanged':
                    /* HANDLE AS DESIRED */
                    break;
            }
        },
        /*
         * callback function: paymentFormLoaded
         * Triggered when: SqPaymentForm is fully loaded
         */
        paymentFormLoaded: function() {
            /* HANDLE AS DESIRED */
            console.log("The form loaded!");
        }
    }
});

function buildForm() {
    if (SqPaymentForm.isSupportedBrowser()) {
        var paymentDiv = document.getElementById("form-container");
        if (paymentDiv.style.display === "none") {
            paymentDiv.style.display = "block";
        }
        paymentform.build();
        paymentform.recalculateSize();
    } else {
        // Show a "Browser is not supported" message to your buyer
    }
}

Please help me so I can sort out this error as soon as possible.

I thank you for your time and look forward to a swift response from you.

Thanks and regards
Sunil
Developer

**Comment by StephenJosey** [comment]
@sunilkumarambala are you calling `requestCardNonce` on the button click? Can you confirm that you're actually getting to the `cardNonceResponseReceived` function? Are you seeing any browser console errors before or after you click submit?
