### ISSUE TITLE
Missing client by that `client_id`

### ISSUE THREAD

**Issue by noname1997** [square/connect-api-examples#63]
new to using oauth i copied the code OAuthhandler and im getting missing client id when ever i click on it, can i find an id somewhere or do i need to make an acount or something? anything helps thx

**Comment by noname1997** [comment]
this occurs after i click on the "Click here" to authorize the application.

**Comment by StephenJosey** [comment]
`client_id` is the same as your `application_id` (can be found here in your dashboard - https://connect.squareup.com/apps). It should be replaced in the code - for example in the PHP Oauth it looks like this in index.php:
```
$applicationId = 'REPLACE_ME';
```
