### ISSUE TITLE
java.lang.IllegalStateException: The " sandbox-id" environment variable 

### ISSUE THREAD

**Issue by pradeepjadi** [square/connect-api-examples#69]
squareAppId = mustLoadEnvironmentVariable(SQUARE_APP_ID_ENV_VAR);

        // Configure OAuth2 access token for authorization: oauth2
        OAuth oauth2 = (OAuth) squareClient.getAuthentication("oauth2");
        oauth2.setAccessToken(mustLoadEnvironmentVariable(SQUARE_ACCESS_TOKEN_ENV_VAR));

        squareLocation = lookupCardProcessingLocation();
    }

 
    private String mustLoadEnvironmentVariable(String name) {
       String value = System.getenv(name);
        if (value == null || value.length() == 0) {
            throw new IllegalStateException(
                String.format("The %s environment variable must be set", name));
        }

        return value;
    }
===================================================================
java.lang.IllegalStateException: 
    String value = System.getenv(name);      
       ------- here getting null value exception java code when calling
      squareAppId = mustLoadEnvironmentVariable(SQUARE_APP_ID_ENV_VAR); 
How can i get    /* model.put("addId", squareAppId);*/ vallue of     "squareAppId"

**Comment by pradeepjadi** [comment]
private String mustLoadEnvironmentVariable(String SQUARE_APP_ID_ENV_VAR) {
   String value = System.getenv(SQUARE_APP_ID_ENV_VAR);
    if (value == null || value.length() == 0) {
        throw new IllegalStateException(
            String.format("The %s environment variable must be set", name));
    }

    return value;
}
======================================
when we cal 
String value = System.getenv(name); 
the value returning null 
i replaced id and access token with my squareup values
SQUARE_APP_ID=replace_me SQUARE_ACCESS_TOKEN=replace_me

**Comment by StephenJosey** [comment]
@pradeepjadi can you please confirm that you are running the program in your console window like so (and not from your IDE):
```
SQUARE_APP_ID=replace_me SQUARE_ACCESS_TOKEN=replace_me mvn spring-boot:run
```
Environment variables will return null if they were set after the process trying to run them was open. In other words, if you opened your IDE, and then set your environment variable, and then tried to run the program from your IDE, your IDE would not know that the environment variable existed. However, in our case, we are running a new instance of spring-boot so it shouldn't matter. With that said, if it's still not working after running the above command, please try restarting your IDE, and running the command again.

**Comment by pradeepjadi** [comment]
after uploading server getting form error(SQUAREUP PAYMENT FORM NOT LOADING)
below error page files:
![screenshot 47](https://user-images.githubusercontent.com/36497042/43850401-7655ecda-9b55-11e8-8ae7-2001b3705522.png)
![screenshot 48](https://user-images.githubusercontent.com/36497042/43850402-7680e4b2-9b55-11e8-899d-5e24b4936651.png)

the same page in my localhost no error shown
my localhost files: SQUAREUP PAYMENT FORM LOADING IN MY LOCAL HOST)
![screenshot 45](https://user-images.githubusercontent.com/36497042/43850513-c8a87b24-9b55-11e8-87a1-c445dadd395c.png)
![screenshot 46](https://user-images.githubusercontent.com/36497042/43850514-c8d28356-9b55-11e8-85e0-b69dc3c82001.png)

**Comment by StephenJosey** [comment]
@pradeepjadi when you're not using localhost, you must have an SSL certificate to enable HTTPS on your web page. Please see https://docs.connect.squareup.com/basics/https-overview#using-tls-and-https for more information.
