### ISSUE TITLE
Error when Running Maven with Java 10

### ISSUE THREAD

**Issue by sargsyan-garegin** [square/connect-api-examples#73]
I followed the instructions in the README to run **connect-api-examples/connect-examples/v2/java_payment/** locally. The following command fails when Maven runs on Java 10:

```bash
SQUARE_APP_ID=replace_me` SQUARE_ACCESS_TOKEN=replace_me mvn spring-boot:run
```

[Here](https://gist.github.com/sargsyan-garegin/83dc6621a17e034647ce23ff96290894) is the full verbose output.

Output of `java --version`:

```bash
java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

It worked fine when I ran maven with Java 8.

**Comment by StephenJosey** [comment]
Can you try with the latest Java example? It was updated yesterday. It should work with Java 8, 9, or 10. I believe it was due to an old version of the Spring Framework. Let me know if it still doesn't work, or if you have any other questions!
